name = "javascript"
extensions = [".js", ".mjs", ".cjs", ".jsx"]
shebangs = ["node"]
line_comments = ["//"]
doc_markers = ["/**"]
regex_literals = true

[[block_comments]]
open = "/*"
close = "*/"

[[strings]]
delim = '`'
multiline = true
escape = '\'

[[strings]]
delim = '"'
escape = '\'

[[strings]]
delim = "'"
escape = '\'
